// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1cQMTUFaYagGqwE9XfQAqhZan62m-SIg',
    appId: '1:1006878898505:web:ed78860db5278f49098298',
    messagingSenderId: '1006878898505',
    projectId: 'flutter-revo-firsttest',
    authDomain: 'flutter-revo-firsttest.firebaseapp.com',
    storageBucket: 'flutter-revo-firsttest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADoLjMbf9091dJmaOwtpnZe7i-GztC3cA',
    appId: '1:1006878898505:android:35c66b643663e44a098298',
    messagingSenderId: '1006878898505',
    projectId: 'flutter-revo-firsttest',
    storageBucket: 'flutter-revo-firsttest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgDVfMHz_XPN6AeCJlLWx8w2xLG6s_QZY',
    appId: '1:1006878898505:ios:49a27deba3d1a294098298',
    messagingSenderId: '1006878898505',
    projectId: 'flutter-revo-firsttest',
    storageBucket: 'flutter-revo-firsttest.appspot.com',
    iosClientId: '1006878898505-v0smp6j3ed94llu8nostq4gilt75vosc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgDVfMHz_XPN6AeCJlLWx8w2xLG6s_QZY',
    appId: '1:1006878898505:ios:49a27deba3d1a294098298',
    messagingSenderId: '1006878898505',
    projectId: 'flutter-revo-firsttest',
    storageBucket: 'flutter-revo-firsttest.appspot.com',
    iosClientId: '1006878898505-v0smp6j3ed94llu8nostq4gilt75vosc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
